### ISSUE TITLE
Add scaling transform to social icons and navigation buttons

### ISSUE THREAD

**Issue by SherRao** [LaurierCS/Website#103]
It would be nice if the social media icons and navbar section names scaled up slightly when you hovered over them. If someone can apply this CSS to the buttons, that would be great:

```css
button {
    transition: all .2s ease-in-out;
}


button:hover {
    cursor: pointer;
    transform: scale(1.5);
}
````
